[phases.setup]
nixPkgs = ['nodejs_20']

[phases.build]
cmds = [
  'echo "Building frontend..."',
  'cd frontend && rm -rf node_modules && npm install --legacy-peer-deps && npm run build',
  'echo "Building backend..."',
  'cd backend && npm install && npx prisma generate && npm run build'
]

[start]
cmd = 'cd backend && npx prisma migrate deploy && npm start'
