[phases.setup]
nixPkgs = ['nodejs_20']

[phases.build]
cmds = [
  'cd frontend && npm install && npm run build',
  'cd backend && npm install && npx prisma generate && npm run build'
]

[start]
cmd = 'cd backend && npx prisma migrate deploy && npm start'
