[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "cd backend && npx prisma migrate deploy && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
