[build]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm install && npm run build && cd ../backend && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "cd backend && npx prisma migrate deploy && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
